django_todo/urls.py
from django.conf.urls import url
from django.contrib import admin
from todo.views import get_todo, create_an_item

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', get_todo),
    url(r'^add$', create_an_item),
]

todo/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=30, blank=False)
    done = models.BooleanField(blank=False, default=False)

    def __str__(self):
        return self.name

todo/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import Item

# Create your views here.
def get_todo(request):
    results = Item.objects.all()
    return render(request, "todo_list.html", {'items': results})

def create_an_item(request):
    if request.method == "POST":
        new_item = Item()
        new_item.name = request.POST.get('name')
        new_item.done = 'done' in request.POST
        new_item.save()
        return redirect(get_todo)

    return render(request, "add_item.html")

todo/templates/add_item.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie-edge">
	<title>Add Item</title>
</head>

<body>
	<h1>Add a new item...</h1>
	<form method="POST">

        {% csrf_token %}

		<label for="id_name">Name:</label>
		<input type="text" name="name" id="id_name"><br>
		<label for="id_done">Done? </label>
		<input type="checkbox" name="done" id="id_done"><br>
		<br>
		<button type="submit">Save</button>
	</form>
</body>

</html>

todo/templates/todo_list.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie-edge">
	<title>TODO List</title>
</head>

<body>
	<h1>Things I need to do...</h1>

	<table>
		{% for item in items %}
		<tr>
			{% if item.done %}
			<td><s>{{ item.name }}</s></td>
            {% else %}
            <td>{{ item.name }}</td>
            {% endif %}
		</tr>
        {% empty %}
        <p>You have nothing to do.</p>
		{% endfor %}
	</table>
    <a href="add">Add an Item</a>
</body>

</html>